In [2]:
import numpy as np
from numpy.random import rand

In [9]:
#1 write a numpy program and find the product of 2d arrays and 3d array
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12],[13,14,15]])
x,y
np.dot(x,y)


array([[ 66,  72,  78],
       [156, 171, 186]])

In [3]:
#2 do a simple calculation using sin,cos,tan,log

In [17]:
a = np.random.rand(5,3)
a

array([[0.85297492, 0.92308365, 0.62337758],
       [0.57267054, 0.97832071, 0.89149696],
       [0.58806822, 0.0381996 , 0.88850147],
       [0.68442449, 0.52662027, 0.93444725],
       [0.34125605, 0.30444894, 0.65201491]])

In [18]:
np.cos(30)/a

array([[0.18083937, 0.16710452, 0.24744465],
       [0.26935461, 0.15766962, 0.17302521],
       [0.26230197, 4.038038  , 0.17360855],
       [0.22537395, 0.2929083 , 0.1650724 ],
       [0.45201089, 0.50665787, 0.23657657]])

In [19]:
np.sin(45)/a

array([[ 0.99757156,  0.92180543,  1.36498897],
       [ 1.48585174,  0.86975929,  0.95446599],
       [ 1.44694697, 22.27519268,  0.95768387],
       [ 1.24323944,  1.61578195,  0.91059557],
       [ 2.493446  ,  2.79489736,  1.30503692]])

In [21]:
np.tan(90)/a

array([[ -2.33910794,  -2.16145136,  -3.20062906],
       [ -3.48402836,  -2.03941345,  -2.23803389],
       [ -3.39280436, -52.23091964,  -2.2455792 ],
       [ -2.91515051,  -3.78868898,  -2.13516644],
       [ -5.84663753,  -6.55348133,  -3.06005336]])

In [26]:
np.log(5)/a

array([[ 1.88685256,  1.74354503,  2.58180267],
       [ 2.81040806,  1.64510257,  1.8053207 ],
       [ 2.73682179, 42.13232002,  1.81140715],
       [ 2.35152004,  3.05616401,  1.72234218],
       [ 4.716218  ,  5.28639692,  2.46840662]])

In [63]:
#3 write a numpy program to multiply a 5x3 matrix using matmul
m = np.array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [1, 2, 1],
        [3, 4, 5]])
 
n = np.arange(1,16).reshape(3,5)
m,n

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 1],
        [3, 4, 5]]),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]))

In [64]:
np.matmul(m,n)

array([[ 46,  52,  58,  64,  70],
       [100, 115, 130, 145, 160],
       [154, 178, 202, 226, 250],
       [ 24,  28,  32,  36,  40],
       [ 82,  94, 106, 118, 130]])

In [36]:
#4 write a numpy program to create a 3x3 identity matrix
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
#5 write a numpy program to create a 3x3 matrix with values ranging from 2 to 10
d = np.arange(2,11)
d

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
d.reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [50]:
#6 write a numpy program to create a new shape to an array without changing its data(for example a 3x2 matrix to a 2x3 matrix)
d = np.array([[1,2],
             [4,5],
             [7,8]])
d.shape

(3, 2)

In [51]:
d.reshape(2,3)

array([[1, 2, 4],
       [5, 7, 8]])